[package]
authors = ["realityone <realityone@me.com>"]
name = "libnetkeeper"
version = "0.1.0"
description = "The netkeeper toolkits write in rust."
documentation = "https://github.com/realityone/libnetkeeper"
homepage = "https://github.com/realityone/libnetkeeper"
readme = "README.md"
keywords = ["netkeeper", "singlenet", "ghca", "srun3k", "drcom"]
categories = ["encoding", "cryptography"]
license-file = "LICENSE"

[dependencies]
byteorder = "1.1.0"
chrono = "0.4.0"
linked-hash-map = "0.3.0"
md4 = "0.4.1"
rand = "0.3.15"
rust-crypto = "0.2.36"

[dependencies.clippy]
optional = true
version = "*"

[features]
default = ["netkeeper", "singlenet", "drcom", "ghca", "srun3k", "ipclient"]
dev = ["default", "clippy"]
drcom = []
ghca = []
ipclient = []
netkeeper = []
singlenet = []
srun3k = []

[lib]
name = "netkeeper"
